Update Rotary2024-cicd.yml

diff --git a/.github/workflows/Rotary2024-cicd.yml b/.github/workflows/Rotary2024-cicd.yml
--- a/.github/workflows/Rotary2024-cicd.yml
+++ b/.github/workflows/Rotary2024-cicd.yml
@@ -55,4 +55,33 @@ jobs:
 
       - name: Replace URLs in CKEditor
         run: |
-          sed -i
+          sed -i "s|https://localhost:44323/Image/CKGetAllImages|https://${{ secrets.URLINSUREROTARYOCEANIA }}/Image/CKGetAllImages|g" DealEngine.WebUI/wwwroot/ckeditor/ckeditor5-techcertain/build/ckeditor.js
+          sed -i "s|https://localhost:44323/Image/_|https://${{ secrets.URLINSUREROTARYOCEANIA }}/Image/_|g" DealEngine.WebUI/wwwroot/ckeditor/ckeditor5-techcertain/build/ckeditor.js
+          sed -i "s|https://localhost:44323/Image/CKUpload|https://${{ secrets.URLINSUREROTARYOCEANIA }}/Image/CKUpload|g" DealEngine.WebUI/wwwroot/ckeditor/ckeditor5-techcertain/build/ckeditor.js
+          sed -i "s|https://localhost:44323/Image/|https://${{ secrets.URLINSUREROTARYOCEANIA }}/Image/|g" DealEngine.WebUI/wwwroot/ckeditor/ckeditor5-techcertain/build/ckeditor.js
+
+      - name: Test SSH Connection
+        run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.URLINSUREROTARYOCEANIA }} "echo 'SSH Connection Successful'"
+
+      - name: Execute Deploy Preparation Script
+        run: ssh ubuntu@${{ secrets.URLINSUREROTARYOCEANIA }} './DE-DeployPrep.sh'
+
+      - name: Copy Login Text File
+        run: cp ~/general/_LoginText.cshtml DealEngine.WebUI/Views/Account/_LoginText.cshtml
+
+      - name: Publish Project
+        run: |
+          dotnet publish DealEngine.WebUI/DealEngine.WebUI.csproj -c Release --no-restore -o ./publish_output
+          ls -la ./publish_output  # Debugging step to ensure output exists
+
+      - name: Deploy Files via Rsync
+        run: |
+          if [ -d "./publish_output" ]; then
+            rsync -azhe "ssh -o StrictHostKeyChecking=no" ./publish_output/ ubuntu@${{ secrets.URLINSUREROTARYOCEANIA }}:/home/ubuntu/projects/dealengine
+          else
+            echo "⚠️ Error: Publish directory not found! Skipping rsync."
+            exit 1
+          fi
+
+      - name: Execute Final Deploy Script
+        run: ssh ubuntu@${{ secrets.URLINSUREROTARYOCEANIA }} './DE-DeployFin.sh'
